# -*- coding: utf-8 -*-
"""segurosParte02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odumVo-tD0sU84qfhNoMlXrVrpKvZGU2

**Nome**:Giovana Giovanin CP3026337

**Nome**:Maria Eduarda Ribeiro Padovani Loschi CP3025811

1. Motivação e Contexto do Problema
Contexto: O mercado de seguros de saúde utiliza dados demográficos e de estilo de vida para calcular o risco e o custo de cuidados médicos.
Relevância: Prever custos com precisão permite que a empresa precifique as apólices de forma competitiva, evitando prejuízos ou valores abusivos para o cliente.
variáveis : A análise pode revelar quais comportamentos (como fumar) ou condições (como o IMC elevado) geram os maiores gastos, auxiliando em políticas de prevenção e planos de saúde personalizados.

2. Detalhamento da Base de Dados


Origem: Dataset clássico de custos médicos (comumente usado em aprendizado de máquina).



O que cada linha representa: Cada linha é o registro de um beneficiário individual do seguro.

Atributos e Tipos:

age: Idade (Inteiro).

sex: Gênero (Categórico/Texto: male, female).

bmi: Índice de Massa Corporal (Numérico/Float).

children: Número de filhos/dependentes (Inteiro).

smoker: Fumante ou não (Categórico/Texto: yes, no).

region: Região de residência (Categórico/Texto).

charges: Custos médicos faturados (Numérico/Float)

**Perguntas:**

 Fumantes têm custos médicos mais altos?

 O IMC (bmi) influencia os custos?

 Existe diferença de custo entre homens e mulheres?

Ter filhos aumenta os custos médicos?

**2.2. Critérios de Avaliação**

*Qual o problema que o grupo trabalhará?*

O mercado de seguros de saúde utiliza dados demográficos e de estilo de vida para calcular o risco e o custo de cuidados médicos. Relevância: Prever custos com precisão permite que a empresa precifique as apólices de forma competitiva, evitando prejuízos ou valores abusivos para o cliente.

*Qual sua motivação? Por que ele é relevante?*

A análise pode revelar quais comportamentos (como fumar) ou condições (como o IMC elevado) geram os maiores gastos, auxiliando em políticas de prevenção e planos de saúde personalizados.

*Perguntas em aberto se pretende explorar/analisar:*

Quais perguntas em aberto se pretende explorar/analisar?

Existem interações entre variáveis (por exemplo, entre IMC e tabagismo) que amplificam os custos médicos?

A região geográfica influencia os custos do seguro de saúde?
"""



"""*Descrição da base de dados escolhida*

*   Onde a base foi obtida (link/fonte)?

https://www.kaggle.com/datasets/mirichoi0218/insurance

*   O que cada linha representa?

Uma pessoa

*   Quais são os principais atributos (colunas) e seus tipos?

Origem: Dataset clássico de custos médicos (comumente usado em aprendizado de máquina).

O que cada linha representa: Cada linha é o registro de um beneficiário individual do seguro.

Atributos e Tipos:

age: Idade (Inteiro).

sex: Gênero (Categórico/Texto: male, female).

bmi: Índice de Massa Corporal (Numérico/Float).

children: Número de filhos/dependentes (Inteiro).

smoker: Fumante ou não (Categórico/Texto: yes, no).

region: Região de residência (Categórico/Texto).

charges: Custos médicos faturados (Numérico/Float)

**Preparação da base de dados (limpeza inicial)**

*   Houve dificuldades para preparar o dataset para uso (ex .: nomes de colunas ruins, arquivos desorganizados)?

Não houve dificuldade, os dados estão organizados.

*   Que ajustes iniciais foram feitos (correção de tipos, remoção de duplicatas, tratamento de
valores inválidos/absurdos)?

Não houve necessidade de nenhum ajuste, as iformações estão corretas.

*   Houve dados faltantes? Como foram tratados (ex .: remoção de linhas, imputação simples)?

Nenhum dado faltante, todas aa linhas estão preenchidas

*   Algum outlier/ruído foi removido/assinalado? Como e por quê?

Nenhum outlier foi removido nem assinalado.

**Análise exploratória**

**Perguntas**

1  Fumantes têm custos médicos mais altos?

2   O IMC (bmi) influencia os custos?

3  Existe diferença de custo entre homens e mulheres?

4   Ter filhos aumenta os custos médicos?

 5  A região geográfica influencia os custos do seguro de saúde?

6 Qual a distribuição de idade dos segurados?

7 Existe interação entre fumar + IMC nos custos?

8  Quais variáveis parecem ter maior influência sobre os custos médicos?
"""

import pandas as pd

df = pd.read_csv("segurosdatabase.csv")


print("--- Estrutura da Base ---")
display(df.head())


print("\n--- Verificação de Valores Nulos ---")
print(df.isnull().sum())

print("\n--- Verificação de Duplicatas ---")
print(f"Total de linhas duplicadas: {df.duplicated().sum()}")


print("\n--- Resumo dos Dados ---")
display(df.describe())

"""Graficos:

1- "Fumantes têm custos médicos mais altos?"

**Resposta:**

Para analisar essa questão, foi feita uma comparação entre os custos médicos (charges) de fumantes e não fumantes.
Observou-se que a média de custos dos fumantes é significativamente maior do que a dos não fumantes.
Além disso, os fumantes apresentam maior variação nos custos, indicando maior risco financeiro.
Isso mostra que o tabagismo é um dos principais fatores que influenciam o aumento dos gastos com saúde.
"""

import seaborn as sns
import matplotlib.pyplot as plt


sns.set_theme(style="whitegrid")
plt.figure(figsize=(9, 6))


ax = sns.boxplot(
    x='smoker',
    y='charges',
    data=df,
    hue='smoker',
    palette={'yes': '#ff4d4d', 'no': '#2ecc71'}, # Vermelho e Verde
    width=0.6,
    legend=False
)


plt.title('Distribuição de Custos Médicos: Fumantes vs. Não Fumantes', fontsize=15, fontweight='bold', pad=20)
plt.ylabel('Custos Médicos ($)', fontsize=12)
plt.xlabel('Status de Tabagismo', fontsize=12)


plt.xticks([0, 1], ['Fumante', 'Não Fumante'])


sns.despine(left=True)

plt.show()

"""**Justificativa:**


 O boxplot foi utilizado pois permite comparar a distribuição dos custos entre dois grupos, evidenciando diferenças de mediana, dispersão e presença de outliers.

2 - "O IMC (bmi) influencia os custos?"

**Resposta:**

Para investigar essa relação, foi analisada a associação entre o IMC (bmi) e os custos médicos (charges).
Observa-se uma tendência de aumento dos custos conforme o IMC cresce, indicando uma correlação positiva entre essas variáveis.
No entanto, a dispersão dos dados mostra que o IMC não é o único fator determinante dos custos.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(x='bmi', y='charges', hue='smoker', data=df)
plt.title('IMC vs Custos Médicos (Fumante vs Não Fumante)')
plt.show()

"""🔵 não fumante
🟠 fumante

**Justificativa:**

O boxplot foi utilizado pois permite comparar a distribuição dos custos entre dois grupos, evidenciando diferenças de mediana, dispersão e presença de outliers.

3 - "Existe diferença de custo entre homens e mulheres?"

**Resposta:**

 Para analisar essa questão, foi feita uma comparação dos custos médicos entre os gêneros (sex).
Observou-se que não há diferença significativa nos custos entre homens e mulheres, indicando que o sexo não é um fator determinante no aumento dos gastos médicos.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="whitegrid")


sns.boxplot(x='sex', y='charges', data=df, hue='sex', palette='Set2', legend=False)

plt.title('Custos Médicos por Sexo', fontsize=14)
plt.xlabel('Sexo', fontsize=12)
plt.ylabel('Custos (Charges)', fontsize=12)

plt.show()

"""**Justificativa:**

 O boxplot é adequado para comparar distribuições entre grupos, permitindo analisar diferenças de mediana e dispersão.

4 - "Ter filhos aumenta os custos médicos?"

**Resposta:**

 Para analisar essa questão, foi feita uma comparação entre o número de filhos (children) e os custos médicos (charges).
Observa-se que não há um aumento significativo nos custos conforme o número de filhos cresce.
As médias de custos permanecem relativamente semelhantes entre os grupos com diferentes quantidades de filhos.
Isso indica que o número de dependentes não é um fator determinante para o aumento dos gastos médicos individuais.
"""

import seaborn as sns
import matplotlib.pyplot as plt


df_pt = df.copy()
df_pt['children_pt'] = df_pt['children'].map({
    0: '0 Filhos',
    1: '1 Filho',
    2: '2 Filhos',
    3: '3 Filhos',
    4: '4 Filhos',
    5: '5 Filhos'
})


sns.set_theme(style="whitegrid")
plt.figure(figsize=(10, 6))


ax = sns.barplot(
    x='children_pt',
    y='charges',
    data=df_pt,
    hue='children_pt',
    palette='mako',
    legend=False,
    order=['0 Filhos', '1 Filho', '2 Filhos', '3 Filhos', '4 Filhos', '5 Filhos']
)


plt.title('Custos Médicos por Quantidade de Filhos', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Número de Dependentes (Filhos)', fontsize=12)
plt.ylabel('Custos Médicos Médios ($)', fontsize=12)

sns.despine(left=True, bottom=True)

plt.show()

"""**Justificativa:**

O gráfico de barras foi utilizado pois permite comparar a média dos custos médicos entre diferentes categorias (quantidade de filhos), facilitando a identificação de possíveis variações entre os grupos.

5- "A região geográfica influencia os custos do seguro de saúde?"
"""

import pandas as pd
df = pd.read_csv("segurosdatabase.csv")
print(df['region'].unique())

import seaborn as sns
import matplotlib.pyplot as plt


traducao = {
    'southwest': 'Sudoeste',
    'southeast': 'Sudeste',
    'northwest': 'Noroeste',
    'northeast': 'Nordeste'
}
df['Regiao_Exibicao'] = df['region'].map(traducao)

sns.set_theme(style="whitegrid")
plt.figure(figsize=(10, 6))


ax = sns.barplot(
    x='Regiao_Exibicao',
    y='charges',
    data=df,
    hue='Regiao_Exibicao',
    palette='viridis',
    legend=False
)


plt.title('Média de Custos Médicos por Região', fontsize=15, fontweight='bold', pad=20)
plt.xlabel('Região Geográfica', fontsize=12)
plt.ylabel('Custos Médicos Médios ($)', fontsize=12)



sns.despine(left=True, bottom=True)
plt.show()

"""**Justificativa:**

 O gráfico de barras é adequado para comparar médias entre categorias, facilitando a visualização de diferenças entre regiões.

6 - "Qual a distribuição de idade dos segurados?"

**Resposta:**


Resposta:
A análise da distribuição etária revela que a base de clientes é composta por uma vasta gama de idades, com uma concentração notável de jovens adultos (em torno dos 18-20 anos). A presença equilibrada de diversas faixas etárias é fundamental para a seguradora, pois permite diluir o risco atuarial. No entanto, o volume de jovens pode indicar um grupo com menor histórico de saúde, enquanto a distribuição contínua até os 64 anos sugere uma base madura que tende a ter custos mais previsíveis, porém potencialmente elevados.
"""

import seaborn as sns
import matplotlib.pyplot as plt


sns.set_theme(style="white")
plt.figure(figsize=(10, 6))


ax = sns.histplot(
    df['age'],
    bins=20,
    kde=True,
    color='#440154',
    line_kws={'linewidth': 3}
)


plt.title('Distribuição de Idade dos Segurados', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Idade (Anos)', fontsize=12)
plt.ylabel('Frequência (Quantidade de Pessoas)', fontsize=12)


sns.despine()

plt.show()

"""**Justificativa:**

O Histograma foi selecionado por ser a ferramenta estatística mais eficiente para representar a distribuição de uma variável numérica contínua (idade). Diferente de um gráfico de barras comum, ele agrupa os dados em intervalos (bins), permitindo identificar visualmente a densidade da população, a presença de modas (picos de frequência) e a simetria dos dados. A inclusão da linha de estimativa de densidade de kernel (KDE) auxilia na percepção da forma da distribuição, facilitando a identificação de tendências que orientam o cálculo de risco do seguro.

7- "Existe interação entre fumar + IMC nos custos?"

**Resposta:**

 Para analisar essa interação, foi observada a relação entre IMC (bmi) e custos médicos (charges), diferenciando fumantes e não fumantes.
Observa-se que indivíduos fumantes com IMC elevado apresentam os maiores custos médicos.
Isso indica que a combinação entre tabagismo e alto IMC potencializa significativamente os gastos com saúde, evidenciando uma interação entre essas variáveis.
"""

import seaborn as sns
import matplotlib.pyplot as plt


df_pt = df.copy()
df_pt['smoker'] = df_pt['smoker'].map({'yes': 'Fumante', 'no': 'Não Fumante'})


sns.set_theme(style="ticks")
plt.figure(figsize=(10, 6))


sns.scatterplot(
    x='bmi',
    y='charges',
    hue='smoker',
    data=df_pt,
    palette={'Fumante': '#E74C3C', 'Não Fumante': '#2ECC71'},
    alpha=0.7,
    s=60,
    edgecolor='w'
)


plt.title('Relação entre IMC e Custos Médicos', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('IMC (Índice de Massa Corporal)', fontsize=12)
plt.ylabel('Custos Médicos ($)', fontsize=12)


plt.legend(title='Status de Tabagismo', title_fontsize='11', loc='upper left')


sns.despine()

plt.grid(True, linestyle='--', alpha=0.5)

"""**Justificativa:**  
O gráfico de dispersão com diferenciação por cor permite visualizar simultaneamente três variáveis, sendo ideal para identificar interações entre elas.

8-" Quais variáveis têm maior influência sobre os custos médicos?"

**Resposta:**

A análise final revela que o custo médico não é definido por uma única variável, mas pela combinação estratégica de fatores. O gráfico de dispersão abaixo demonstra que:

Não Fumantes (Verde): Mantêm custos baixos (abaixo de $15.000) independentemente do IMC, com um crescimento muito sutil conforme a idade ou peso aumentam.

Fumantes (Vermelho): São divididos em dois grupos críticos. Aqueles com IMC abaixo de 30 já gastam o dobro dos não fumantes. No entanto, ao ultrapassar a marca de 30 de IMC (obesidade), os custos saltam para a faixa de $30.000 a $60.000.
Portanto, a interação entre Tabagismo e IMC elevado é o principal preditor de alto risco financeiro para a seguradora.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="whitegrid")
plt.figure(figsize=(11, 7))


ax = sns.scatterplot(
    x='bmi',
    y='charges',
    hue='smoker',
    data=df,
    palette={'yes': '#ff4d4d', 'no': '#2ecc71'},
    s=80,
    alpha=0.7,
    edgecolor='w'
)


plt.legend(
    title='Fumante?',
    labels=['Sim', 'Não'],
    loc='upper left',
    title_fontsize='12',
    fontsize='10'
)


plt.title('Influência Combinada: IMC e Tabagismo nos Custos', fontsize=15, fontweight='bold', pad=20)
plt.xlabel('Índice de Massa Corporal (IMC)', fontsize=12)
plt.ylabel('Custos Médicos ($)', fontsize=12)

sns.despine()
plt.show()

"""**Justificativa:**  

Esta visualização utiliza um Gráfico de Dispersão Multivariado, que é a ferramenta mais sofisticada da Análise Exploratória para identificar clusters (agrupamentos) e interações não lineares. Ao cruzar os dados de IMC (numérico) com o status de fumante (categórico), conseguimos provar que o impacto do IMC não é constante, mas sim condicionado ao comportamento do segurado. A inclusão da linha vertical no IMC 30 serve como um suporte visual para a tomada de decisão de negócio, segmentando os clientes em faixas de risco claras.

CONCLUSÃO:

Após a realização da análise exploratória dos dados de seguros, destacam-se os seguintes pontos fundamentais:


1.   O Impacto Predominante do Tabagismo: O hábito de fumar demonstrou ser a variável com maior influência isolada nos custos médicos. Fumantes apresentam medianas de custos drasticamente superiores e uma dispersão de dados muito maior que não fumantes.

2.   A Interação Crítica entre IMC e Tabagismo: Observou-se que o Índice de Massa Corporal (IMC) elevado, quando associado ao tabagismo, potencializa exponencialmente os gastos. Indivíduos não fumantes conseguem manter custos relativamente baixos mesmo com IMC elevado, o que sugere que o risco financeiro é amplificado por comportamentos de estilo de vida.


1.   Variáveis de Baixa Influência: Diferente do esperado, variáveis como o sexo do beneficiário e a região geográfica apresentaram impactos mínimos ou irrelevantes na média de custos. Isso indica que a precificação baseada puramente em demografia pode ser menos eficiente que a baseada em indicadores de saúde e comportamento.

1.   Limitações do Dataset: Uma limitação observada é a falta de dados históricos de saúde mais profundos (como doenças pré-existentes), o que poderia explicar alguns outliers de alto custo encontrados mesmo em grupos de baixo risco (não fumantes com IMC normal)

Conclusão para Modelagem: Para a próxima etapa (Parte 2), as variáveis smoker, bmi e age devem ser as principais candidatas para o treinamento dos modelos preditivos, visto que possuem a correlação mais forte com a variável-alvo charges.

**--------------------------------------------------PARTE 02-----------------------------------------------------------**

No pipeline de Aprendizado de Máquina, a preparação correta dos dados é crucial. Definimos a variável charges (custos médicos) como o nosso alvo preditivo (target), caracterizando uma tarefa de Regressão.

Rigor Técnico contra Data Leakage:
Realizamos a divisão da base em 80% para treino e 20% para teste utilizando random_state=42 para reprodutibilidade. Esta divisão foi feita antes de qualquer normalização ou codificação. Isso impede o Data Leakage (vazamento de dados), garantindo que informações do conjunto de teste (como médias do scaler) não contaminem o aprendizado do modelo.

Estruturamos um ColumnTransformer para aplicar o StandardScaler nas variáveis numéricas e o OneHotEncoder(drop='first') nas categóricas de forma segura através de pipelines no passo seguinte.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer


df = pd.read_csv("segurosdatabase.csv")

X = df.drop(columns=['charges']) # Atributos
y = df['charges']                # Variável-alvo (Target)

# 3. Divisão Treino/Teste (80% para treino e 20% para teste)
# O random_state garante que o resultado seja sempre o mesmo (Reprodutibilidade)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Configurar as transformações das colunas
colunas_numericas = ['age', 'bmi', 'children']
colunas_categoricas = ['sex', 'smoker', 'region']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), colunas_numericas),          # Normalização
        ('cat', OneHotEncoder(drop='first'), colunas_categoricas) # Transformar texto em número
    ]
)

"""Neste passo, definimos e treinamos 3 técnicas distintas utilizando Pipeline para garantir que o pré-processamento seja isolado corretamente para cada modelo:

Linear Regression: Nosso modelo simples usado como baseline.

Random Forest Regressor: Técnica baseada em comitê de árvores (Bagging).

Gradient Boosting Regressor: Abordagem avançada de comitê sequencial (Boosting), utilizada para buscar o ponto extra (+1) por não ter sido aprofundada em sala.
"""

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Definir os 3 modelos
modelos = {
    'Linear Regression (Baseline)': LinearRegression(),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Gradient Boosting (Ponto Extra!)': GradientBoostingRegressor(random_state=42)
}

# Treinar e avaliar cada um deles de forma consistente
resultados = []

for nome, modelo in modelos.items():
    # O Pipeline garante que o pré-processamento seja aplicado corretamente sem vazamento de dados
    pipeline_modelo = Pipeline(steps=[('preprocessor', preprocessor),
                                      ('regressor', modelo)])

    # Treinamento
    pipeline_modelo.fit(X_train, y_train)

    # Predição
    y_pred = pipeline_modelo.predict(X_test)

    # Cálculo das métricas exigidas
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    resultados.append({
        'Modelo': nome,
        'MAE (Erro Médio)': mae,
        'RMSE': rmse,
        'R² Score (Precisão)': r2
    })

# Exibir a tabela comparativa estruturada
df_resultados = pd.DataFrame(resultados)
print(df_resultados.to_string(index=False))

"""Analise


1.    Desempenho dos Modelos e Comparação com o BaselineO nosso modelo baseline (Regressão Linear) apresentou um $R^2$ de 0.7835, o que significa que ele consegue explicar aproximadamente 78,3% da variabilidade dos custos médicos. No entanto, os modelos baseados em árvores superaram o baseline significativamente.O Random Forest alcançou um $R^2$ de 0.8656 (86,5% de precisão) e o Gradient Boosting obteve o melhor desempenho de todos, com um $R^2$ de 0.8792 (87,9% de precisão).

2.  Por que os modelos de árvore foram melhores?
Essa diferença ocorre porque a Regressão Linear tenta assumir uma relação estritamente reta e aditiva entre as variáveis. Contudo, como observamos na nossa Análise Exploratória de Dados (Parte 1), variáveis como smoker (tabagismo) combinadas com um bmi (IMC) elevado não aumentam os custos de forma linear, mas sim de forma explosiva/não-linear. Os algoritmos de árvores de decisão conseguem criar quebras e capturar essas interações complexas de maneira muito mais eficiente.

3.  Interpretação Prática do MAE (Erro Médio Absoluto)
Olhando para a perspectiva do negócio de seguros de saúde:

*  O modelo de Regressão Linear erra, em média, $4.181,19 por apólice calculada.
*   O Gradient Boosting reduziu esse erro médio para $2.443,48.


Na prática, utilizar o Gradient Boosting em vez da Regressão Linear faz com que a empresa reduza o seu erro de previsão em quase $1.737,00 por cliente. Isso evita que a seguradora cobre valores abusivos dos clientes ou sofra prejuízos por precificar apólices abaixo do custo real de risco.

4.   Justificativa do Ponto Extra (+1)
Como oportunidade de explorar técnicas avançadas além do escopo tradicional de sala de aula, implementamos o Gradient Boosting Regressor. Enquanto o Random Forest cria várias árvores independentes em paralelo (Bagging), o Gradient Boosting constrói árvores de forma sequencial, onde cada nova árvore é treinada especificamente para corrigir os erros cometidos pelas árvores anteriores. Essa abordagem de aprendizado focado nos resíduos justificou o maior poder preditivo e o menor erro (RMSE de 4329.57) entre todas as técnicas testadas

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------

Para avaliar a capacidade de generalização e otimizar nosso modelo, aplicamos uma busca exaustiva de parâmetros usando GridSearchCV com Validação Cruzada de 5 dobras (5-fold Cross Validation) no algoritmo Random Forest
"""

from sklearn.model_selection import GridSearchCV

# Criar o pipeline para o Random Forest
pipeline_rf = Pipeline(steps=[('preprocessor', preprocessor),
                              ('rf', RandomForestRegressor(random_state=42))])

# Definir quais parâmetros testar
param_grid = {
    'rf__n_estimators': [50, 100, 150],
    'rf__max_depth': [None, 5, 10]
}

# Executar a busca com Validação Cruzada de 5 dobras (cv=5)
grid_search = GridSearchCV(pipeline_rf, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(X_train, y_train)

print(f"Melhores parâmetros: {grid_search.best_params_}")
print(f"Melhor R² na Validação Cruzada: {grid_search.best_score_:.4f}")

"""Estratégia de Otimização e Ajuste de Hiperparâmetro                                


Para buscar o melhor desempenho possível e entender a capacidade de generalização do modelo, aplicamos uma estratégia de busca exaustiva de hiperparâmetros utilizando o GridSearchCV focado no algoritmo Random Forest.  A busca utilizou a estratégia de Validação Cruzada com 5 dobras (5-fold Cross-Validation). Isso significa que os dados de treino foram divididos em 5 partes, onde o modelo foi treinado em 4 e testado na parte restante, rotacionando esse processo 5 vezes.  Interpretação dos Resultados:Melhores Parâmetros Encontrados: O algoritmo identificou que limitar a profundidade máxima das árvores em 5 níveis (max_depth: 5) com 150 estimadores (n_estimators: 150) traz o melhor equilíbrio.
* Análise do $R^2$ (Validação Cruzada): O valor de 0.8442 (84,42%) obtido na validação cruzada é uma métrica extremamente robusta e realista. Embora seja ligeiramente menor que o $R^2$ de teste direto do modelo puro (que foi de 86,56%), essa proximidade nos dá a segurança estatística de que o modelo não está sofrendo de Overfitting (decorando os dados de treino) e possui alta capacidade de prever custos de novos clientes na vida real.


Parâmetros Otimizados: O Grid Search identificou que limitar a profundidade máxima em 5 níveis (max_depth: 5) com 150 estimadores evita complexidade desnecessária no modelo.Análise de Robustez: O $R^2$ obtido na Validação Cruzada foi de 0.8442 (84,42%). Por usar validação cruzada (onde o modelo é testado em fatias diferentes dos dados de treino), essa métrica é mais realista e segura.

Como ficou muito próxima do valor de teste puro (86,56%), comprova-se que o nosso modelo não sofre de Overfitting (decorar dados de treino) e está pronto para generalizar com novos dados de clientes.
"""